#!/usr/bin/env python
import os
import shutil
import subprocess
import sys


src = sys.path[0] + '/src'
home = os.environ['HOME']
liquidprompt_src = os.path.join(home, '.liquidprompt')

for file in os.listdir(src):
    source = os.path.join(src, file)
    destination = os.path.join(home, '.' + file)

    print "linking %s to %s..." % (source, destination)

    if os.path.islink(destination) or os.path.isfile(destination):
        print "notice: removing existing file at %s..." % destination
        os.remove(destination)
    elif os.path.isdir(destination):
        print "notice: removing existing directory at %s..." % destination
        shutil.rmtree(destination)

    os.symlink(source, destination)

if os.path.exists(liquidprompt_src):
    print 'Updating liquidprompt...'
    os.chdir(liquidprompt_src)
    subprocess.check_call('git pull', shell=True)

print 'SUCCESS!'
print 'You should run ". ~/.bashrc"'
