#!/usr/bin/env python2
"""Take a picture on git commit."""
import os
import subprocess


keepcharacters = (' ', '.', '_', '-')
picture_dir = os.path.expanduser(os.path.join('~', 'Pictures', 'gitshots'))

if not os.path.exists(picture_dir):
    os.makedirs(picture_dir)


def git(*args):
    """Subprocess helper for running git."""
    return subprocess.check_output(['git'] + list(args))


repository_name = os.path.basename(os.getcwd())
clean_repository_name = "".join(c for c in repository_name.lstrip('.') if c.isalnum() or c in keepcharacters).rstrip()

commit_hash, commit_date = git('log', '-1', '--pretty=%H %at').strip().split(' ', 1)

picture_name = "{commit_date}_{repo_name}_{commit_hash}.jpeg".format(
    repo_name=clean_repository_name,
    commit_date=commit_date,
    commit_hash=commit_hash,
)

print("Say Cheese!")

picture_filepath = os.path.join(picture_dir, picture_name)

try:
    # TODO: put a timer on this. sometimes this hangs forever
    subprocess.check_call(['imagesnap', '-q', picture_filepath])
except OSError:
    print("imagesnap is not installed.")

print(("gitshot saved to {}".format(picture_filepath)))
print("")
