if [ -n "$HOMEBREW_BREW_FILE" ]; then
    echo "Bypassing .bashrc because of brew"
    return 0
fi

source $HOME/.bash/dispatch.sh

# use .localrc for settings specific to one system
if [ -r "$HOME/.bashrc.local" ]; then
    source $HOME/.bashrc.local
fi

# use settings installed by Chef
[ -e "$HOME/.profile" ] && . "$HOME/.profile"
