" based on https://github.com/jferris/config_files/blob/master/vimrc
execute pathogen#infect()
syntax on
filetype plugin indent on

" pretty format json with the help of python
map <leader>js <Esc>:%!python -mjson.tool<CR>

" Local config
if filereadable(".vimrc.local")
  source .vimrc.local
endif

